Fix/tech 220 balance breakdown
chain4travel/camino-wallet pull request #14
Opened 2022-09-22 21:46 UTC by Ayagoumi

2022-11-20 23:33 UTC, c4t-ag requested changes, later dismissed
This PR has to wait until we have re-implemented getBalances API function

2022-11-20 23:33 UTC, c4t-ag commented on src/store/modules/assets/assets.ts
> -        walletPlatformBalanceLocked(state, getters, rootState): BN {
Please remove instead commenting out -> github will still remember...

2022-11-24 08:28 UTC, c4t-ag commented on package.json
> -        "@c4tplatform/camino-wallet-sdk": "file:../camino-wallet-sdk/package",
No

2022-12-15 18:54 UTC, Noctunus approved these changes
Code wise it looks fine from my side

2022-12-16 08:26 UTC, merged