Enable Abort Button in Add Validator and Register Validator
chain4travel/camino-wallet pull request #259
Opened 2023-05-12 15:26 UTC by Esteban100k

Enabled the Abort Button in the Add Validator and Register Validator transactions

2023-05-12 15:58 UTC, aeddaqqa requested changes
can you please use the abort signin modal you can find it in src/components/wallet/earn/ModalAbortSigning.vue so we will have unified abort functionality in all pending trxs

2023-05-12 19:44 UTC, aeddaqqa requested changes
- there is a duplication of the phrase : 
<img width="747" alt="Screenshot 2023-05-12 at 20 37 33" src="https://github.com/chain4travel/camino-wallet/assets/51858084/fecbbc96-a104-46b2-a51f-50c05648f8ae">
<img width="589" alt="Screenshot 2023-05-12 at 20 35 04" src="https://github.com/chain4travel/camino-wallet/assets/51858084/dac00cfd-9c4f-44f9-95cb-608c91451514">
- also if i aborted the tx with the second user the reload button disappear and i need to logout and login again to check if the section is updated
- if i register a validator with the first user and the second is already logged the reload button does not work

2023-05-15 13:34 UTC, aeddaqqa submitted a review, later dismissed

2023-05-15 14:57 UTC, rafaelkordonias requested changes

2023-05-15 14:57 UTC, rafaelkordonias commented on src/components/wallet/earn/Validate/PendingMultisig.vue
>                      message: 'Transaction has been cancelled',
Please use translations and not hardcoded text here

2023-05-15 15:31 UTC, Esteban100k commented on src/components/wallet/earn/Validate/PendingMultisig.vue
>                      message: 'Transaction has been cancelled',
@rafaelkordonias Translations are now used

2023-05-15 15:39 UTC, aeddaqqa approved these changes

2023-05-16 13:26 UTC, rafaelkordonias approved these changes

2023-05-16 13:27 UTC, merged