Disable obsolete cypress test
chain4travel/camino-wallet pull request #265
Opened 2023-05-23 15:04 UTC by Esteban100k

In this PR, cypress tests are disabled from the camino-wallet repository.
This is because the cypress tests that are updated are those from the camino-suite repository, so these tests that are in camino-wallet become obsolete.

2023-05-23 15:10 UTC, rafaelkordonias approved these changes

2023-05-24 11:43 UTC, Ayagoumi approved these changes

2023-05-24 11:48 UTC, mo-c4t requested changes
we need to change the workflow file if we will skip these tests inside the wallet. do we have the tests on camino-suite running ?

2023-05-24 11:52 UTC, mo-c4t commented
@Esteban100k  if we are skipping all these tests, why don't we delete them ?

2023-05-24 13:46 UTC, closed without merging