feat(account): create settings component to manage account from suite
chain4travel/camino-wallet pull request #282
Opened 2023-06-09 09:15 UTC by aeddaqqa

2023-06-09 20:34 UTC, Esteban100k requested changes
I think the text is too big to be in the account Menu selector.

![image](https://github.com/chain4travel/camino-wallet/assets/52749037/c236969c-f96e-4690-b9f9-c519b3d170da)

2023-06-09 21:03 UTC, Esteban100k approved these changes, later dismissed

2023-06-12 14:08 UTC, rafaelkordonias submitted a review, later dismissed
LGTM

2023-06-13 15:01 UTC, Esteban100k approved these changes
LGTM

2023-06-13 20:59 UTC, Ayagoumi approved these changes

2023-06-14 08:53 UTC, Ayagoumi approved these changes

2023-06-14 09:28 UTC, merged