Main branch rename
chain4travel/camino-wallet pull request #65
Opened 2023-02-04 00:55 UTC by mo-c4t

2023-02-04 01:00 UTC, mo-c4t commented
replace foundation with network domain
deleting old workflows for creating dockers
renaming main branch to c4t

2023-02-04 01:15 UTC, havan approved these changes
Looks good to me

2023-02-04 13:48 UTC, c4t-ag requested changes

2023-02-04 13:48 UTC, c4t-ag commented on .github/workflows/build.yaml
> -name: build-app
IMO a good source for ideas - I'm against removal

2023-02-04 13:48 UTC, c4t-ag commented on .github/workflows/docker.yml
> -name: docker
Why is this one removed?

2023-02-06 08:44 UTC, c4t-ag approved these changes

2023-02-06 08:49 UTC, merged